language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
  - "6"
install:
  - travis_retry npm install -g esy@latest
  - travis_retry make bootstrap
script:
  - esy install
  - esy build
  - esy make test